mastery:
  gem:
    points-per-block: 1000
    levels:
      1: 100000
      2: 200000
      3: 300000
    rewards:
      1:
        - "give %player% diamond 1"
      2:
        - "give %player% emerald 1"
      3:
        - "give %player% netherite_ingot 1"
  smire:
    points-per-block: 1200
    levels:
      1: 200000
      2: 400000
      3: 600000
    rewards:
      1:
        - "give %player% diamond 2"
      2:
        - "give %player% emerald 2"
      3:
        - "give %player% netherite_ingot 2"