name: MineMastery
version: 1.0.0
main: com.keksy.minemastery.MineMastery
api-version: 1.19
depend: [EZBlocks, Vault, PlaceholderAPI]
description: Un plugin de maîtrise de minage avec des compétences et des récompenses.
authors: [AlexiMth]
website: https://skymines.fr
commands:
  mm:
    description: Commande principale pour MineMastery
    usage: /mm <subcommand>
    aliases: [minemastery]
    subcommands:
      stats:
        description: Affiche les points de maîtrise d'un joueur ou de tous les joueurs depuis la console
        usage: /mm stats [joueur]
      addpoints:
        description: Ajoute des points de maîtrise à un joueur
        usage: /mm addpoints <joueur> <points>
      reload:
        description: Recharge la configuration de MineMastery
        usage: /mm reload
